main:
  device: cuda
  dataset: truckscenes # scannet, replica, truckscenes
  scene_id: scene-0044384af3d8494e913fb8b14915239e-3 # scene0011_00
  dataset_path: /shared/data/truckScenes/truckscenes_converted
  save_path: /home/daniel/spatial_understanding/benchmarks/HOV-SG
models:
  clip:
    type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: ../checkpoints/laion2b_s32b_b79k.bin 
    # checkpoint: checkpoints/ovseg_clipl14_9a1909.pth checkpoints/laion2b_s32b_b79k.bin
  sam:
    checkpoint: ../checkpoints/sam_vit_h_4b8939.pth
    type: vit_h
    points_per_side: 12
    pred_iou_thresh: 0.88
    points_per_batch: 144
    crop_n_layers: 0
    stability_score_thresh: 0.90 # 0.95
    min_mask_region_area: 50 # 100
pipeline:
  voxel_size: 0.1 # 0.021
  skip_frames: 1
  init_overlap_thresh: 0.01 # 0.75
  overlap_thresh_factor: 0.025
  iou_thresh: 0.5 # 0.05
  clip_masked_weight: 0.4418
  clip_bbox_margin: 50 # in pixels
  feature_dbscan_eps: 0.01
  max_mask_distance: -1 # 10000 # 6.4239 in meters
  min_pcd_points: 1 # 100
  depth_weighting: false
  grid_resolution: 0.05
  merge_type: sequential # hierarchical, sequential
  save_intermediate_results: false
  obj_labels: HM3DSEM_LABELS
  merge_objects_graph: false
